/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jakem' at '6/6/17 10:34 AM' with Gradle 2.14.1
 *
 * @author jakem, @date 6/6/17 10:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
